version: '3.9'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "4000:4000" # Map port 4000 for external access
      
    volumes:
      - ./salescoachvalue-1dc80d83e3fb.json:/app/salescoachvalue-1dc80d83e3fb.json:ro

    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/app/salescoachvalue-1dc80d83e3fb.json"
      NODE_ENV: production
