version: '3.9'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "4000:4000" # Map port 4000 for external access
      
    volumes:
      - ./sales-1dc80d83e3fb.json:/app/sales-1dc80d83e3fb.json:ro

    environment:

      NODE_ENV: production
